apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-etc-bind
data:
{{- range $path, $bytes := .Files.Glob "config/etc/bind/*" -}}
{{- $subdir := dir $path }}
{{- $currentFilename := ($path | replace (printf "%s/" $subdir) "" ) }}
{{ $currentFilename | quote | indent 2 }}: |
  {{ tpl ($.Files.Get $path) $ | nindent 4 }}
{{- end -}}
