apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
{{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        {{- include "helm.labels" . | nindent 8 }}
{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
{{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-alpine
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: alpine:3.18
        command:
        - /bin/sh
        - "-c"
        - sleep 7d
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
{{- range $path, $bytes := .Files.Glob "config/etc/bind/*" -}}
{{- $subdir := dir $path }}
{{- $currentFilename := ($path | replace (printf "%s/" $subdir) "" ) }}
        - name: etc-bind-{{ $currentFilename | replace "." "-" }}
          mountPath: /etc/bind/{{ $currentFilename }}
          subPath: {{ $currentFilename }}
{{- end }}
{{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
{{- end }}
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #command:
        #- "/bin/sh"
        #- "-c"
        #- "docker-entrypoint.sh named -c /etc/bind/named.conf -g -u named & sleep 7d"
        ports:
        - name: do53tcp
          containerPort: 53
          protocol: TCP
        - name: do53udp
          containerPort: 53
          protocol: UDP
        - name: rndc
          containerPort: 953
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
{{- range $path, $bytes := .Files.Glob "config/etc/bind/*" -}}
{{- $subdir := dir $path }}
{{- $currentFilename := ($path | replace (printf "%s/" $subdir) "" ) }}
        - name: etc-bind-{{ $currentFilename | replace "." "-" }}
          mountPath: /etc/bind/{{ $currentFilename }}
          subPath: {{ $currentFilename }}
{{- end }}
{{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
{{- end }}
      volumes:
{{- range $path, $bytes := .Files.Glob "config/etc/bind/*" -}}
{{- $subdir := dir $path }}
{{- $currentFilename := ($path | replace (printf "%s/" $subdir) "" ) }}
      - name: etc-bind-{{ $currentFilename | replace "." "-" }}
        configMap:
          name: {{ $.Release.Name }}-etc-bind
          items:
          - key: {{ $currentFilename | quote }}
            path: {{ $currentFilename | quote }}
{{- end }}
{{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
