apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: do53tcp
      port: 53
      protocol: TCP
      targetPort: do53tcp
    - name: do53udp
      port: 53
      protocol: UDP
      targetPort: do53udp
    - name: rndc
      port: 953
      protocol: TCP
      targetPort: rndc
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
