name: Docker buildx CI

env:
  PLATFORMS: linux/amd64
  # BUG: Waiting for https://github.com/docker/roadmap/issues/371
  #PLATFORMS: linux/amd64,linux/arm64

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          [
            alpine,
            #debian,
            #ubuntu
          ]
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Create builder
      run: |
        docker buildx create --platform=$PLATFORMS --bootstrap --use
        docker buildx inspect
    - name: Build image
      run: |
        docker buildx build --load --platform=$PLATFORMS --tag bind9:${{ matrix.distribution }} -f docker/Dockerfile.${{ matrix.distribution }} docker/
